### ISSUE TITLE
Help for understanding the code

### ISSUE THREAD

**Issue by sumanthraikar** [igorauad/symbol_timing_sync#1]
I am a beginner on this topic, I started by just changing modulation to QPSK and tried to receive a signal in real-time using an SDR device.  I observed that usually after symbol timing synchronization the constellation plot has all the points on a unit circle. But in this code, it appeared that frequency offset is also getting corrected which might be the reason for an ideal QPSK constellation.
 
I just want to know if I am thinking in the right direction or not and I couldn't identify where was frequency offset correction?

**Comment by igorauad** [comment]
Hi @sumanthraikar , 

Thanks for your interest in this work and apologies for the long delay. In case you are still studying this topic and using this repository, yes, you are definitely thinking in the right direction.  The simulation in this repository simply does not introduce any frequency offset, so the receiver does not experience any. There is no need for (and no implementation of) frequency offset correction since this phenomenon is not simulated. The goal here is mainly to understand the components of a symbol timing recovery loop while evaluating them in nearly ideal conditions (aside from AWGN).

By the way, in case you are interested, I have been looking at this code again lately and I've pushed various updates, covering other timing error detectors that were missing and reviewing the implementation in general. 

Regards
